---
- name: Hello world
  debug: msg="Hello {{ ansible_hostname }}!"

# - template:
#     # Template file uses Jinja2 syntax
#     src: config.json.j2
#     dest: /opt/pagemonitor.json

#stop running process if it exists
#from https://stackoverflow.com/questions/46515704/how-to-kill-a-running-process-using-ansible
- name: Get running processes
  shell: "ps -ef | grep -v grep | grep -w {{ process_name }} | awk '{print $2}'"
  register: running_processes

- name: Kill running processes
  shell: "kill {{ item }}"
  with_items: "{{ running_processes.stdout_lines }}"

- wait_for:
    path: "/proc/{{ item }}/status"
    state: absent
  with_items: "{{ running_processes.stdout_lines }}"
  ignore_errors: yes
  register: killed_processes

- name: Force kill stuck processes
  shell: "kill -9 {{ item }}"
  with_items: "{{ killed_processes.results | select('failed') | map(attribute='item') | list }}"


#just in case
- name: Delete previous install directory
  become: yes
  file:
    dest: /opt/pagemonitor/
    state: absent

- name: Initialize install directory
  become: yes
  file:
    dest: /opt/pagemonitor/
    state: directory

- name: Add pagemonitor.py
  become: yes
  copy:
    src: pagemonitor.py
    dest: /opt/pagemonitor/
    owner: root
    group: root

- name: execute pagemonitor script
  command: python3 /opt/pagemonitor/pagemonitor.py
