---
- name: Hello world
  debug: msg="Hello {{ ansible_hostname }}!"

# - template:
#     # Template file uses Jinja2 syntax
#     src: config.json.j2
#     dest: /opt/pagemonitor.json

- name: Stop running jobs
  become: yes
  file:
    dest: /opt/pagemonitor/
    state: absent

- name: Initialize install directory
  become: yes
  file:
    dest: /opt/pagemonitor/
    state: directory

- name: Add pagemonitor.py
  become: yes
  copy:
    src: pagemonitor.py
    dest: /opt/pagemonitor/
    owner: root
    group: root

#install requirements
- pip:
    name: gevent
    virtualenv: "{{ virtualenv_path }}"

- name: execute pagemonitor script
  command: python3 /opt/pagemonitor/pagemonitor.py
