---
#stop running process if it exists
#from https://stackoverflow.com/questions/46515704/how-to-kill-a-running-process-using-ansible
- name: Get running processes
  shell: "ps -ef | grep -v grep | grep -w {{ process_name }} | awk '{print $2}'"
  register: running_processes

- name: Kill running processes
  become: yes
  shell: "kill {{ item }}"
  with_items: "{{ running_processes.stdout_lines }}"

- wait_for:
    path: "/proc/{{ item }}/status"
    state: absent
  with_items: "{{ running_processes.stdout_lines }}"
  ignore_errors: yes
  register: killed_processes

- name: Force kill stuck processes
  become: yes
  shell: "kill -9 {{ item }}"
  with_items: "{{ killed_processes.results | select('failed') | map(attribute='item') | list }}"


- name: Initialize install directory
  become: yes
  file:
    dest: "{{ install_location }}"
    state: directory

- name: Add pagemonitor.py
  become: yes
  copy:
    src: pagemonitor.py
    dest: "{{ install_location }}"
    owner: root
    group: root

- name: Add config.json
  become: yes
  copy:
    src: config.json
    dest: "{{ install_location }}"
    owner: root
    group: root

- name: Execute pagemonitor script
  become: yes
  shell: "python3 {{ install_location }}{{ process_name }} &"
